def count_similarities(dna1, dna2):
    count = 0
    for a in range(len(dna1)):
        if (dna1[a] == dna2[a]):
            count += 1
    return (count)

def are_parents(p1, p2, child):
    for i in range(len(child)):
        if (child[i] != p1[i]) and (child[i] != p2[i]):
            return (False)
    return (True)

def count_matches(data, i):
    list = {}
    for j in range(1, len(data) + 1):
        if (j != i):
            list[j] = count_similarities(data[i], data[j])
    x = 1
    while (x < len(data)):
        y = 1
        while (x != i) and (y < len(data) + 1):
            if (y != i) and (y != x):
                if (are_parents(data[x], data[y], data[i]) == True):
                    return (list[x] * list[y])
            y += 1
        x += 1
    return (0)

def main():
    data = {
        1: "CTTTTGTCTTAGTAATATACAAATCTAAAAAACGCGAAGAGTATCGGGGTCAAGGGACTGATGAGTGGTCAGGCTCCTGCTGGAGGCATCGTGTAAATAATCATCGCTCTAGCACCACCGTAACTTGT",
        2: "CAGCCCAGTTGGTTGCGTCGGCAGCGCATCTTCAAATTAGTTAGCTGCCCAACCGGCGACCTAGTAAGGGAACTTACGCCGCACCATAGAGAACTACTACAATTGGTTAAGCAAGGGGATCCATTACC",
        3: "GACGCACCTCGGTTGTGCGTACACGTGGGAAGGACGGAGCACTCAAGCGAAAGCGGGTTTGGGTGGACTTCGTGGCCCGTAGGGACCATCCATTAGCACTTGACCTGCGGTGACCATATCGCGCTAGC",
        4: "GACACCGCGTTACTTAAACAACAAGGGATTTGACGACCATAGGCGTGTGCGGGGATTCTTCCTTCCGATGAGCGGGCGCCCCGCCATACGCAACCGTCAATTACTGCACATATGATAGAGGCTCGCAA",
        5: "AGCATGAGACCGGCCGCGTGTCCGGGTAGATACTTATAAGCGCCATTCCACTCGTGGCTCTCGCAGCATATTGTACAGACTATGCATAATTCTTCGAGTTGTATTCACGTGAAGGCGTGCGGTATCGA",
        6: "AAGCGCGGCGCTATAATGTTGTCACCACAGACGATAGGCTTTCCTATGACAGAACAACACTGCCGTTTCGCTCGACCTCCACGAGCATCGTTTATTGCCAAATACCGAAGGGACGAACCCATGACCCG",
        7: "AATAGGCACTCATTAGTATGCACCTTAGATGTCGTGTTTCGGGAAATCATCACACGTCTTAAATGCCGATTGTCCGGGAGATATCTGTCCCCATATAGTTCGACGGCGGCAATCGTTCGTCTTTGATA",
        8: "AAATGACACTCAGTAGAGAGGACATTAGAAGTCGTGCGTCGGGAAATGAAATTAAGTGTTAGCTGCCGATGTGTAGTGTAATAACTAACTCAGCATGGTTCCACTCGGGCACTCGTTCTTCTTAAATA",
        9: "CGCCCCAAATCGTTGGGTAGGAAACGCATCTAAATATTAGTCTCCTGCCGAACGAGCGACCTAGTGAAGGTACTTAGGCGGCTCCATGGGGAACTACCACGAAAGGACAAGCAAGAAGTTCCAGAGCC",
        10: "CACAGCTGCTTCACATAATCTGTTGTCTAGTTTTTAGAACGCGCGTTGTCTGATAAACTCACCAAGGACTCCTGTAAAGAACTGTCTCTCAACGGGGTGTCGGTCTTCATGGTCTGGAGTACCCGAAT",
        11: "TAAATTGCGGCCCATACTCCACAGGCGTGATGATGTGAGTTTCCAATGATCCGCCTGGTGTAGTGTTCCCTTTTTTTATATGTGCCAACTAAGCAATATCTTTAGTTTTATTCCGTAGCTTATGAGTA",
        12: "ATTAATATAAATTCTAATCTGCCCCAGGTTTAATTTAGGCTCCCGATACCCCCCGCGGTAGCGTTAGGCCCTCCCTCGACACATTACACGTCATTGACACTACTAGCAGGATCCCCTAGGAAAGCTTA",
        13: "TACTCATAGCTATTTTGCTTCGATGTGGGAAGGACGCACATTTACTGCTAAAGCTAGTTCGGGTGTACTTCTTATTCCGTGGGGACCTACGACTTAGACTACACCTGCGAGGACCGCGACTGGCTAGC",
        14: "GAACCAGGGCCTTCGACAACAGTCTACCGTGCGTGGTGAGTCAGTCGGGAATCGACGACGGCGGCATCGGTGAAACATTACTGTGAAAGGATTATGGGCAGCTGCTTTCAGGTGTAGAAAGAAGTAAC",
        15: "CTCCCTGACAAGTCGCTTGAAATCGGCGTTCGACCGAGATCGGAACGCACGTGGCCAAGGTCTAGCAGAACGAAATCTAGTATCGGCCATTTCGCAATATCACAGCAGTCGTGCGTATGTGTTCGTGC",
        16: "AGCCGAACTCATCAAGCATGGGTGGGACCACCATTTCCCTCACCTCACTCTGATAACACACATTTGGGCCCATCCCATAGCGAAGGGACTCCCGCGTCCCAATAGCGTCTCCCTCTCCACGTAGGACT",
        17: "GTGCGAATTCCAGGAGTATAACTCGCAAGGCCTAACCTGGTTTCGCGGGGACACCGCTCCCCGACGCTTTCGATATGGAATGGAATTTTGTCTCTCGTTAATCTTAAGTAGATTGAGTTTGAATAAAC",
        18: "TATGCAGAGGACAATCCCTGCGCTTCGCACGATGATATGAGATCGTTTAACTACGTAGCAAGTGCATGCTCATTGACAACCCTAGGCCATGGTCTACTCATCGTTTGGGATTCCCATCTGTATCCATC",
        19: "GATCAGTACGCGGAGACAACCTCCGTAGCTGAAAACGTCGATAGGCCCGGCGGGGGCAGTATGATCGCCCGCGGCTATCCCCGATCGCATAAGTGGTCGCCGAATCTATGCTTGTGGATTCATGTTTC",
        20: "GCCCGCTTCTATTAATATAGCCAACTAATACTGGCGCAGACAATCGGCTTCGGAGGCCTGATGAGTCGTCAATCTGCCCGCTGAGGCCTTTGGTGAATACTCAAGAATCTTACCCCGACGAAACCGCG",
        21: "AAGGCAGTCCAGGTCACAATCAAAGGATACAACAGCCCTGCAGCGACGTATAGTGGTCTCAAGAATGCTATTACCTGAAATTCAGAGTTCACCCGATTGTCTCTTTCGAGGCAGAGGGTGTCCACTAG",
        22: "ATCCATGCCAATTATCGTGAATTACGTGTTCGTGCAGGAACGGAGGGAACGTTATGAAGCTGCAGCAGTATGTGAGGACGTATGGGGCATTGCTTTATATCTCATGACTTCGGCAAATGTTTTGAAGC",
        23: "TGAAATCCGGTGCAATATCACCGCGGATGTTCAGCCGAACTTCGGGGCCATTTGCAATACCAGCCGACCCGTGGCCAGCGACGTTATTCTGCCACTGGGATGGAGGCTGAATTTTGTGCAGTTTTCCG",
        24: "GTACAAATTCGCGGAAGGAAAGCACCATACAAACGGTTCCGACACCGCGCTTCTAGACGAAAACCAGGCAAGAGACAACGCGTAATCGAGTGCCCCATACTCCATTCTCGGCGTAAGGTATTTAGAAT",
        25: "TCACCGGCTGGTACATGATCCCTTTCGTGGAGAGCGGCATAGTATAGAATTGCGCCTAGTGTCACGTACGGACTCTACTGACACTAGTCTATGGTACTATTTACGGCGGGCGTTCCCGCAACGAAGCC",
        26: "GCTCCCGACACTTAAGCGTCACTGCCGCGGTTGGATCTCTGTTCGGCATCCAGGATACAGGTAAGTCATCTTACTCAGCAGAGGCCTATCAATTTACGGACTGGTATGAGCAGCGCTCTCACACGTTA",
        27: "GAGCATCGTACGCGCTATCTCAAAGTCGTCTCAGTCGAAGTTCGGCTGATTTTTTCTTTTAAGTTGACACGGCGCCGGAGGAGTTGCGTCGCGACCGGGCTAGAGTTTGACGGCTGTGTAGCCGTCCC",
        28: "TCTGCGCACTGTACTAGCCGTATGCCCCTTAAGCCAAACCAGGCTATGCTTGTCACTTCTCCTTGGTAAATTCAGTAGAGTCTCGCTATAGCGAACTATCGGCCCCATCAAGATAGTCTGATTGATCA",
        29: "GATCCGAGAGCGGGCTGAACCTACTGAGGGGAAAATGACGTGCGCGATGCCGGGGGCGAGGTGATGGCCGTTGCTATTCCCCGGCCGGTTACGAGGTCGCCCAGTATTATCGTGGGGGTTCCTCCTAT",
        30: "TGTCAAATTATGGCCAGCGCCGCACCCTAATGCCTACTGCGTAAACGAAAATCACGTGCGACGGTGCTAGCGCCATAGTACTAGTGACCTAAGCGGGCGTATCTTATTGGTATTTGAAAGATGTCATT",
        31: "ACTCCACTCTTCCCCCCTATTCCGATAGAATCGCAAGTTAATGTGACCAATCATGGTAACTCGCGATCTTCAATATTCTGGCCCACGGGCTCGGGTGTCCGCATATTTAGAGTGTAACGAGTACACTC",
        32: "CGTGCTTGACCAGACTGATGCGTGGGATTACAAGCACAGTAACTTACCTCTGCTCACGCACAAGCTCGCCCGTAGCATAGCCTAGGCGCAACCGCCCGCGGATGGACCTCCCATATCGAAATATGACA",
        33: "ATTAAGATACATTGTAAAGTGTGCCGCATTTTAATTCGGCAATTTTCACTTTGCGATATTACTTTGCCTGCTCCCTTCAAACATGACACCTAATCGGAACGTCTATGAGGATTCCCTCGAGGGACGCA",
        34: "GCACGGGTACTTTTGGTCAGAGGGTATCATGAGACGTGAGAAATGCGGGAATCTATGTTCGAAGCATGTCAATGTCATAACCCTGAGCTGACTATCGGCAGCTTTTCTGTGGTGTACGTGGGACTTTG",
        35: "TCACCGGTAGGGGCATGCTAGCTTCAACTGAGACCAGCATTGTATGTAAGGTTTTTGAGGGTAACTCTAAGACCAAACTAAACCGGGTCTATTATATGGTTTCCAGCGCTCGTTCCCGCTACCATGGT",
        36: "AAAAGACAGGCATAAGAATACAGATTAGCTATCCTGCGTGCGAAAATCGTATCAAGTCCTTGCAGCTGATTGTTCGGGTGATCTCTATCCCCGTTGGGTTACGTGGGGGCAATCGATTGTCTTAATTA",
        37: "GACGTTTATCCCCGCCAAACGAGTGCTGCTCCAGCTACTTCTGGCACCAAGAGATGGATGATTTAGATCCAAGCATATTTTAAAGCTTGCCTTCAGCAGGTGTTTGCTGATTAGATCCGCCAGTTGGG",
        38: "GTCGCACCTTGGTGGGAAGTACGCATGGGAATAACGGTGCACGCAATCGTCAAGGGCGATTCCCGGGACGTGGGGCATGTAGGGAGAATACCTAAGCTCCTGCGCGCGCGTTAGTATATTGCGTACTA",
        39: "CACAGCTGGTTTTGTGAATCTACCTGCTGGTTATTATAACGTGCGTTCTCTCAATAGCTCATCTACGCGCACTGGACAGTACTGTCTCAAAGTAATGTCTCGGCAGTACTGTTCTGAATTACCGGAAC",
        40: "GAGCATAGTACTCGCCGAGTCAAAGTCGTCGTATTGATGGATCCCCTGATCGATTCTTTTAATTTGCCACTGCTACGGAGGATCTGCGTCGAGAGCGGGCTACAGTTTGTCGGCTGAGTAGCCGTCGC",
        41: "CGGACCAGAGAAGGCTGAATCTATTGTCGGTAATATAATTTGCGCGATGCCCCATCTGAGGCGAAGACAGTTTCTATGGCCTCGCCTGTTTCCAAATTATCCAGCATTATTGCAGGAGATCCTCCAAT",
        42: "TTCGTCTTGTTATCATGCTAAAACCACTTCCCTCAGCGATACAAAGTACACATCAGTCTAGCTTGTGCTCCTGCGAAGTGTTCCCGTCATCCATCCCCCTGACAGGTAGTCGTCGTACACTAAAGCTT",
        43: "CAACGACGGGCTTTGGTCACATGGTCCTGTAAGACTTGTGTCATTCCGGTCGCGGCGATGGCAGCATGGCAAAGACATTTCTCTGGACTCGTATTGGGCAGCTTTTTTCTGGAATACGTACAACTAAC",
        44: "CTAAGGAGATCAGAAGCGTGACCCGGTCGGAAGTGTTCAGGGCTCTTCCTGTACTGGTTCTCGCAGCATGTTATGAAAACTAAGCACATTTCTTGCTTCTAGTCTCACGTTGAGGCCTTCCGTATGGT",
        45: "TGACAGGGTGGTAAGATGTTCGCACCATAAACAATCGACATCCCTAGTTCAAGACAACACATGCGTTTGCCTCTACCATGAACATTATCGTTTATTGACAAGCGGCGAGCGGACGTAACTATTCGCAA",
        46: "CCCTGTCAAAGTTTCATTGAGGGGTCGCGATTTGGCAAGCATCATCGCTGACTCTCGTATCCAATAGGGTTCTACCAACAAATGCTAAACTATCAACTTCAAGGTACTACAGGCACCCGGAAGGATTG",
        47: "GATCCGTGCGAGGACTGAACCTATGTTGCTTAATATGACTTTCGCCCCGGCCCGTCTGGTGTGAACACAGGTTGTATGGCCCCACCTCATTCCAAATTGTCCAGTCTTTTTGTATGGGATCATCCTTC",
        48: "TCTACAGGGAACAATCCCTACCCTCCGAGCTAAGATATGATCTCGACTTACTACGGGGGGAGTCTAGTCCACGGTATGATCCTGGGTAATCGTCAAGTCATGGTTTTGGTTTCCCGACTTGCTCCATC",
        49: "TGAGTGTACTGTACTTGCCTATGGTCCATGCAGACACACCAGCCTATGGTCGCGACAGCGTCCTGGTATCTCTGGTACAGCCTAGCAGACGTTATCACTCGACCCCCTGAGGAAAGTCAAATAGAACA",
        50: "ATTTAGATTCGTTGTCATCTACGTCACGTCTTAATTAGTTAACTTTCAGCTCCCTAGGCTGCGCTAGCCGCCTTCTCCACACAATTCACCTACTCGGAACTACTATGATGAGCCACCAAAGGAATGCG",
        51: "GCCCGCTTCGTTGCATTTTGCCGACGTTTACTGTGGCGTCCATTTGGCTACGGATGCAGGGTAAAACGCCGATGAGGCCGCTTACGCCATTGGCGTGTACACGAGAATCCTACCTAGATAACCTCGCG",
        52: "CATCTCGCCCGAAAAAAACAAGAAGGGATTTGACCAACCTAGGGGAGTGCGCGAATTCCGACTTACTACCCGCGGGCTTCCGGCCAGCTCCAACCGGTAAGCACTGCATACCTGTTGGAGGCACGAAC",
        53: "AGGGACGGTCGGCTGACTTTCGTACCCCAGATAATCAACAATCCTGTGTCAGATCAACACATCCGGTTGGACGGACCTCCCAGATCCTAGCGTATTGACCAACACCGTAGGGATGTACCTATGCCCCG",
        54: "GCTTGCTTTTATGCATATTGAAATCTTTTACTCGGGAATCGTTTTGGCTTCAGGGGCCTGATGAATGGCCAATCTCCCGCCGTACGCAATTTGCGTATAATCAAGACTCCAACACCGATATCACCTCT",
        55: "TCAGCGATTTGGGCATGCCCGCTTTCACTACGTCTAGCATATTATAGAATTGTTCCGAGGGTCACGCTCGCACCATGCTGCACAGGGTCTATGGTATGATTTAAAAGACGCGTTTCACCTCCGAAGGT",
        56: "TACTATCCTGGCCGTTCATCGCAGTCGTAAGGAGGAGCATTTTTTACGAATATTCCACTTTACTGACCCTTTCAGTTTTATGTGACAGCTACGAGATAACCTTAGTTTTAGTCCAAAGCTTAGGAGGA",
        57: "GACTTTAATCCCCGCAATACTCTGGGAAGTCCAGCTACCTCTGGCAGAGAGAGATGTAGGAGTGACATTCGCGCATTTTTGAAAGATCGCTTTCACCATGGGGACGGTGAGTAGGTCATCGCGTTATC",
        58: "AGCAGAGGACCAGCCTCGTGAACCGCTCAAATCGTATCGGCGGCCGAATTGACGTCTTGCTCGCAGGCAATTGTACAAACGCATCTCCATTCCTCGTTCCATATTTAGGAGAAGCCGTGCCATATGGT",
        59: "GGAAATCCTGCTCGCCGTGACAACGGCTTTTTATCCAAAGTTCGCCGGCTTGAGCAATATCAGCCGCCACTGGGACGGCGGCTCTGCTCCGAGACTGGGCTGGAGTTTGTCTTTTGTGCAGCTGTCCG",
        60: "GACGCACATCGATTTTACGTACACATGGGAAGAACGGACCACGCCATCTAAAGGGGCTATTCCCGTGCCTTTTAGCATGTAGGGACATAACCCATAGTCTACCGCTGGCAGGACCGTAACTGGCACGC",
        61: "CGCACTGACGAGCAGCTCGAATTAGATTCTAATCCAAGGACGCAACGAAGGATACCAAGCAGCCCGAGTACTAGAGCACGGAGCGGCCATTTCTTTATATCACATGACTTGGACATATGTTCTCGTGC",
        62: "CACAGCCGGTTTAGAGACTCTACCGGCTAGTCAGTATAGCACACCAGCTCACAATAGAACATCATGGCGCCCACGACAGTACCGTCTTTCAGTAAGTGCTCGGCAGCAATGTGCTTGAGGACCCAAGT",
        63: "GCCCCTCAAAGTTTCGTGGAGCGGTCGCGATTGGATCTCTGTCATCCCTCCATGACACAGCCAATACGTTTCTCTCAGCAAAGGCTAATCAATTAACTGAATGGTACTAGAGGCACTCGCAAGGGTTG",
        64: "AGCCGAACTAATCGAGCTTAGGTCCAACCAACATTTGCCCCAACACACAATAATAAGACCCATTTGGCCCTATCCCTCAATGAATCGAATCCCCAGTCCCAGCAGCGTCTCGCACTTCCCGTGGGACT",
        65: "AAAGTTTATGGCGGCATAACTCTGACAGGTCCTGCCACCTCTAATTCAAATAGTTGTAGGATTTTGGCCTGCGCATATTTGACAGCTTGCCTCCACAAGGTGTACGGTGATTATATCATTCAATTGTC",
        66: "CGGGCAGTCATGGTGAGAATAAAAGGTTAAGAGCCCCCTCCCTCTAAGCCCCTGGCCCTCAAAAATGCGACAGGCTGATATTCAGACTTTACCCGATTGCGTCGTTCGAGGTAGAGGATGTGCACATG",
        67: "CAGCCCGGTTCGTTGCGTAGTAAACGCATCTTCGAACTAGTCACCTCCGGTCCCGGCCACCAAGTGAATATAGTCAGGTCGCACCATGGGGAACTGATTCAATTGGATCAGCAAAGAGTGCCATTGCC",
        68: "TAATATCAGGCCCGCACTCTACAGGCATAGTGTTTAGCATGTCCTTTATATATCCTAGAGAAGTGATCGTTTCAGTCATTTGTCCTAGCTACGAGGTAATTCTAGTCTTTGTGCAAAGCAGAGGGGTA",
        69: "AGCCCCAAATGGTTAGGTCGGCAGCGCATCGAAATATTGTATTGTTGTCCAAGGAGCGGGCTAGTAAGGGATCTTTCACGGCTCCTCACAGTAACACCATGTAACTTCAAACAAGAGGATCCAGAATC",
        70: "TACATAGCTGGCTATTCATCGCACTAGCGAGGAGGTGAGCTTTTAACGATCCGTGCGCTTTACTGTCCCCATTTTTTTTAAGTGACCAAGCATCAAGTTCCTTTTATATATTCCGTTGGTTATTAGGC",
        71: "CTCCGCCGGGTTTGTGACCTGACCTGCGGGCCAGTATGGCATACCAGCTCACAATAGAAGATCTTCGCGCACACGCCAGTAACGTTTTAACGTAATTGCGACTCAGCACTGTGCATATTGATCGAGGC",
        72: "TGGCGAATTATGGCCGTCTCCGTCGCCTGATGCAAACTGCGTTAACGGGAATAACGCGCGACGACGCTTGCGCCATAGTACTAGTGTTCTAATCGGGCTTATCTTATGGGGATTTAGAAGAAGTCAAT",
        73: "ACAGTTTAGGGGGGCCTAACGAGTACTGCTGATTCCGATTATAATTCCACTATTCGGATCGTTTTGGCCTAAGCCTATCTTCCACCTTTACACTAGAAGGTGTTTGCTGATCCTATCCGTCAATTGGG",
        74: "GGTGCGTCCTGGTTTTGCGTAATGTCCAATAAGACACAGGTGCTTAGGGTTGCCAATTATTGTTGACATCTTCAATACGGCCAAGCAGTAGCGGAGTATCGGCCCGATGAGGCAAGTCTAGTACATCC",
        75: "CCTTCCGACAGTTACACTGCAGGGTCGCGGTTGGATCACTATTCGCGCTGCCGCTCACAGGTAATAGGGCTTACTCAACAAATGCCTAACAATTTACTGCATGGTATGAGAGGCGCTCGCACACGTTA",
        76: "GCACCCACTAGAGGATTGAATGATCAGTCAAATCGCCTCCAACTCTACGCTGATATTCGCAAACTAGGCATGTAACATTGCGTCATCGTGCTCCGAGTATTCCATTCACGGCGTGAGGTTTTTAGAAT",
        77: "GTATAAGTGCACGATAGGTGAGCAACAGACAAAAGGTTCGGGAATCGTGGATCAAGATAAGATCCATACTAGAGAACACGCGTAACGGATTGGCCCATACTGTCTCCTTCGGGCAAGCAACGCCAAAC",
        78: "TCTACATGGAACACTGCCTGCCCTTGAAACGATGATATTATCTCGTTTAACTAAGTAGGGGGCGTAGTATACTTTATAATCCTAGTTCAAGGCCTCGACCTGGTTTGACACACGCGAATTTAACCATC",
        79: "GTTCGAATTCCAGCAGGCGCCGCACCAAAACCTAACCTGGTTAAACGGAGACAACGCTCCCCGATGCTATCGCTATAGAACTGAATATTGTCGCTCGTTAATCTTAAGGGTATTGAGTATAAATCATC",
        80: "GTACAAGTTAAAGAAATGTGTGATAAAGCAAAAAGGCTCGAGATTTGTGCATAAAGATGCAAACCATACTTGAGAACTCGCGTAATCGAGCGGCCCGTATTCTATCCTTCGGGCAAGGATTGCCAAAC",
        81: "ACTCCACCCTTACCCCCTATTCCCTTAGAATCGCACCATACCATGACTACACCTGAAATCGTATGACGTTCCGTATTAAGGCCTACTCGCTCTCCTGTATACAATACTAGAGAGCCCCGAGTCCAGAC",
        82: "TATCCACCTTGACCTCCTCTTCCCTTTGAAGTGACCGTTACCATCACCAATCCTCGACACGTATGATGTGCAGTTTTAAGGCCTACTGCCTATGCTAACTACATAACTCGAGATCCACGAGTACTCTC",
        83: "AGCATAGGTCAGGCCTATTGTAGGACCAAATTCGTACAGGCAGCAGAATACACGGCTCGTTCGGAGGCAATTGAACCGACGCTTCTTCAAGGCTCGAGTCGTATTTAGGAGAGCCCGTGCGAACTCGA",
        84: "GACACGACGTTGCTTGGTCGCCCTAAACCGTGGGGACAATAGACCTCTCATGGGATATTTCATGCCGCTGAGAGGCGGCAGCACTCTACGCATTGTTCATTTAATACACATATGAGAAGCGGTCACAA",
        85: "GCTACGCCTTAGTTTAGCGGTATACTCCATAATCCTAAGGTCGTGAGGCTTCTCTATTATCGTGGACAAAATCAATAGGGTGACGCTATATCGGAGTAGAGGCCCGAGCTATCTCTTCTGGTTCATAC",
        86: "TCAGACATATGGGCTTGCCAGCCTCAACTACGTCTAGCTTTTTAGGTAGGGTTTTTGACGGAACCTCTAACACCAAGAGACACAGGCTGTAATATATGGTGTCAAAGACTCACGTCACGTCCCTTGGT",
        87: "GGGTCGCTGGAATAGCTCACTTTGTACCGTTAGTAGATCCAGATAAGTCTGACGCACGTCCGGGGCCTGGTCGGCAAAAATGGGCTGGCATCGCAAGCACACCCTGCCCATTTAGTCCCATGCCAACT",
        88: "CATCCGGCGTTAAATAGTCAAGCAGAAATTTGGGCACACTAGGCGTCTCATGGGATATCGCATGACTCCCAGCGGCCGTCGCGCTAGACCCATTCTGTATGCACTACATACCTGATGGGGGGACAAAA",
        89: "TCGACATGTAATTCAGCCTACCTACGAAGCTTAGATATTCTCAGGACTTCGTAAGGGGGGGCCCTGGTACACGGTATGATCCTGATTAAACCCCACGACCTGTTCTTACTCACGTGAATTGCACCATG",
        90: "AAGGGCGGCCCGCTATCTCGGTTAGCCCAGGTGATAAGGTATTTTGTGACAGATGAGCACTGCCTGTGCGACGGACATCCCCGAGCCCAACGTCTTGCTCCATACCGTAGTGCTGAACGCAAGACACG",
        91: "CGTGCCAAGATCTGGCGCCCAAGCACTGGAGCGCCGAGCCGCTGTCACCCCCTGTCCACGATACACGGGTCAGGGCCTTGTTCAAGCTGTAGCCTATCCCGTAGGTACAGGTCTGACACTAGGACATT",
        92: "AATATGCAGGACTACGTATACGGCTAGGCTATCCTGTTAGCGAAAAACGTCACACATCCTTAAAGATCATTGTCCTGGAGTTCTCGGTCCCCATTGATATAGGTGGCGACAATCGAATGGCTTTGTTA",
        93: "CCATGGCTAGTATTTGTCAGATGGACTTAAAAGACTTGTGAACTGTCGCTCGTTGTTTTCGAACCTTGTCAATGTTATATCCCAGGGCTCGCATTCGTCATATTTGCTGTTGAATACGTGCGACTTTG",
        94: "ATCTATCTTAGGTCTCATCTACCTCAGGTCTAATATACTTTCCCGATTGCCCCCTCGGCAGCGCTAGGCCACTTGTCGGCATCATTCACGTCCTTAACGATACGTGCTTAGGCAACCAAGAAAGTTTG",
        95: "CGCACGTACGAGCCGCTCTCAATCGACTCGAAACAGAGGTCGCCACACGGCAGGCCGGGGACTCCGACAACTAACTCTATGAGCGTCTAATTTGCAATGTGACAGCGGTCGTACGTATGTGCACGTGC",
        96: "GGCTTGCTGGTATCATTCTCAAACTACCGTTAGCAGCTATAGATAATTCTGATCCACCTCCCGTGCGTTGTCGGCAAATATTCGCGTGCATCACACCCCTAACCGGCCGTTGTAGTACAATGAAGCTT",
        97: "TTGGCCTTGGTATCATGCACTATGTACTGCCCGTAGATCCAGATAATTCTGATGCGTCTACCGTGTCCTCTCGGGAAATGTGCCCTGCATCCATACCCCCGCCCGGCCCTTGTCGTACACTGCAGACT",
        98: "CGCGCATGTCAACGCTGTTGCGTCCAACTAACATCTCCCTAAACACCCAATGATCAGACACATGCGCCCCCGTCGCTTAACGAAGGGGCAACCCACCCCGGATGGCCTTTCGCACTCCACGTATGACT",
        99: "TACGGAACTTGAGATCGTCAGACCTTTGAGGTGACCCATCCCATCACTACACCCCAACTAGTATGACGTGCCGTTTTAAATCCTACTCCATATCCTAAATAAAATACTCGTGATCCCCGATCCCTGAC",
        100: "AGGGCAATGCTCTTCCGCCTCAACAGATACGAGCGGAGTCGCTCTCAGTACCTTTCCATGATGCACGCGTTTGGCCGATGTTCAAACTGCACCCTATCCTGTAGTTCCAGGTATAAGATGTGGACATG",
    }
    index = []
    for i in range(1, len(data) + 1):
        index.append(count_matches(data, i))
    print(sum(index))
    return

if __name__ == "__main__":
    main()
